version: '2'

services:
  remote_selenium:
    platform: linux/amd64
    container_name: remote_selenium
    image: crawler:1.0
    shm_size: 2gb
    ports:
      - 4444:4444
    networks:
      - our_net

networks:
  our_net:
    driver: bridge



